name: Tests

on:
  push:
    branches:
    - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test Versions
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [buntu-18.04, ubuntu-20.04, ubuntu-22.04, ubuntu-latest]
        versions: [4.1.0, v4.1.0]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup APICTL
      uses: ./
      with:
        version: ${{ matrix.version }}
    - name: Validate apictl Version - ${{ matrix['version'] }}
      run: apictl version | grep ${{ matrix['version']}}