name: Tests

on:
  push:
    branches:
    - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test APICTL Versions on different OS versions
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-latest]
        version: [4.1.0, 3.2.6, v3.1.5] # mixing the versions with "v" and without to test
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup APICTL
      uses: ./
      with:
        version: ${{ matrix.version }}
    - name: Validate apictl version - ${{ matrix['version'] }}
      run: apictl version | grep ${{ matrix['version']}}//v/ # Replacing the v in version. 
